### PR TITLE
fix: deleting events with dependent objects

### LINKED ISSUE #366: Naprawa EventsController
**Metoda `destroy`**: Implementacja obsługi błędów integralności relacyjnej oraz weryfikacja istnienia obiektów zależnych przed próbą usunięcia rekordu nadrzędnego.

### PR DESCRIPTION
**Pull request by kamilramocki**
Closes #366 

----

> [!IMPORTANT]
> Enhances `destroy()` in `events_controller.ts` to prevent deletion of events with participants or dependencies, adding transaction management and error handling.
> 
>   - **Behavior**:
>     - In `destroy()` of `events_controller.ts`, added check to prevent deletion of events with registered participants, returning a conflict response.
>     - Added transaction to delete related `emails`, `forms`, and `attributes` before deleting the event.
>     - Catches database error `23503` to handle deletion conflicts due to dependent objects, returning a conflict response.
>   - **Misc**:
>     - Minor refactoring in `destroy()` to improve error handling and transaction management.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=Solvro%2Fbackend-eventownik-v2&utm_source=github&utm_medium=referral)<sup> for 661ba7bf71a9cdf595ed7a4e00d0a0c91262e1a8. You can [customize](https://app.ellipsis.dev/Solvro/settings/summaries) this summary. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

File: app/controllers/events_controller.ts [hunk 1]
```diff
@@ -263,8 +263,43 @@ export default class EventController {
...
+    const participants = await event
+      .related("participants")
+      .query()
+      .count("* as total")
+      .first();
+
+    if (participants !== null && Number(participants.$extras.total) > 0) {
+      return response.badRequest({
+        message: "Cannot delete event with registered participants",
+      });
```
Comment (loudsheep) [inline app/controllers/events_controller.ts]: Tutaj też bym raczej dał `confict` zamiast `badRequest` bo badRequest implikuje że client wysłał źle stworzone zapytanie
